version: "3"

services:
  api:
    build: ./api
    command: npm run start
    deploy:
      replicas: 3
    depends_on:
      - mariadb
      - redis
    ports:
      - "3000"
    restart: unless-stopped
    
  apiLB:
    image: nginx:latest
    volumes:
      - ./apiNginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "4000:4000"
    restart: unless-stopped
    
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: todos
      MARIADB_ROOT_PASSWORD: Mfc2h7BLNz*%!o5C
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build: ./frontend
    deploy:
      replicas: 3
    depends_on:
      - apiLB
    ports:
      - "2000"
    restart: unless-stopped

  frontendLB:
    image: nginx:latest
    volumes:
      - ./frontendNginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - "80:80"
    restart: unless-stopped


networks:
  default:
    driver: bridge